plugins {
    id 'java'
    id 'application'
}

group = 'aczg.grebechi'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'aczg.grebechi.Main'
}

// Permite a interação com o teclado (Scanner) no terminal
tasks.named('run', JavaExec) {
    standardInput = System.in
}